{
  try {
    testExists(domain,rule);
  }
 catch (  AssertionError e) {
    assumeNoException(e);
  }
}
