{
  try {
    test(instance,rule);
  }
 catch (  AssertionError e) {
    assumeNoException(e);
  }
}
